fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.1.0"
    xinetd:
      repo: "git://github.com/puppetlabs/puppetlabs-xinetd.git"
      ref:  "1.2.0"
  symlinks:
    remctl: "#{source_dir}"